export const POPULATION_PAGE = "List of countries and dependencies by population";
export const BORDER_PAGE = "List of countries and territories by number of land borders";
export const CAPITAL_PAGE = "List of national capitals";

export const COUNTRY_NAMES = {
    AFG: "Afghanistan", ALB: "Albania", DZA: "Algeria", AND: "Andorra", AGO: "Angola",
    ATG: "Antigua and Barbuda", ARG: "Argentina", ARM: "Armenia", AUS: "Australia", AUT: "Austria",
    AZE: "Azerbaijan", BHS: "Bahamas", BHR: "Bahrain", BGD: "Bangladesh", BRB: "Barbados",
    BLR: "Belarus", BEL: "Belgium", BLZ: "Belize", BEN: "Benin", BTN: "Bhutan", BOL: "Bolivia",
    BIH: "Bosnia and Herzegovina", BWA: "Botswana", BRA: "Brazil", BRN: "Brunei", BGR: "Bulgaria",
    BFA: "Burkina Faso", BDI: "Burundi", KHM: "Cambodia", CMR: "Cameroon", CAN: "Canada",
    CPV: "Cape Verde", CAF: "Central African Republic", TCD: "Chad", CHL: "Chile", CHN: "China",
    COL: "Colombia", COM: "Comoros", COG: "Republic of the Congo", COD: "Democratic Republic of the Congo",
    CRI: "Costa Rica", CIV: "Ivory Coast", HRV: "Croatia", CUB: "Cuba", CYP: "Cyprus", CZE: "Czech Republic",
    DNK: "Denmark", DJI: "Djibouti", DMA: "Dominica", DOM: "Dominican Republic", ECU: "Ecuador",
    EGY: "Egypt", SLV: "El Salvador", GNQ: "Equatorial Guinea", ERI: "Eritrea", EST: "Estonia",
    SWZ: "Eswatini", ETH: "Ethiopia", FJI: "Fiji", FIN: "Finland", FRA: "France", GAB: "Gabon",
    GMB: "Gambia", GEO: "Georgia", DEU: "Germany", GHA: "Ghana", GRC: "Greece", GRD: "Grenada",
    GTM: "Guatemala", GIN: "Guinea", GNB: "Guinea-Bissau", GUY: "Guyana", HTI: "Haiti",
    HND: "Honduras", HUN: "Hungary", ISL: "Iceland", IND: "India", IDN: "Indonesia", IRN: "Iran",
    IRQ: "Iraq", IRL: "Ireland", ISR: "Israel", ITA: "Italy", JAM: "Jamaica", JPN: "Japan",
    JOR: "Jordan", KAZ: "Kazakhstan", KEN: "Kenya", KIR: "Kiribati", PRK: "North Korea",
    KOR: "South Korea", KWT: "Kuwait", KGZ: "Kyrgyzstan", LAO: "Laos", LVA: "Latvia",
    LBN: "Lebanon", LSO: "Lesotho", LBR: "Liberia", LBY: "Libya", LIE: "Liechtenstein",
    LTU: "Lithuania", LUX: "Luxembourg", MDG: "Madagascar", MWI: "Malawi", MYS: "Malaysia",
    MDV: "Maldives", MLI: "Mali", MLT: "Malta", MHL: "Marshall Islands", MRT: "Mauritania",
    MUS: "Mauritius", MEX: "Mexico", FSM: "Micronesia", MDA: "Moldova", MCO: "Monaco",
    MNG: "Mongolia", MNE: "Montenegro", MAR: "Morocco", MOZ: "Mozambique", MMR: "Myanmar",
    NAM: "Namibia", NRU: "Nauru", NPL: "Nepal", NLD: "Netherlands", NZL: "New Zealand",
    NIC: "Nicaragua", NER: "Niger", NGA: "Nigeria", MKD: "North Macedonia", NOR: "Norway",
    OMN: "Oman", PAK: "Pakistan", PLW: "Palau", PAN: "Panama", PNG: "Papua New Guinea",
    PRY: "Paraguay", PER: "Peru", PHL: "Philippines", POL: "Poland", PRT: "Portugal",
    QAT: "Qatar", ROU: "Romania", RUS: "Russia", RWA: "Rwanda", KNA: "Saint Kitts and Nevis",
    LCA: "Saint Lucia", VCT: "Saint Vincent and the Grenadines", WSM: "Samoa", SMR: "San Marino",
    STP: "São Tomé and Príncipe", SAU: "Saudi Arabia", SEN: "Senegal", SRB: "Serbia",
    SYC: "Seychelles", SLE: "Sierra Leone", SGP: "Singapore", SVK: "Slovakia", SVN: "Slovenia",
    SLB: "Solomon Islands", SOM: "Somalia", ZAF: "South Africa", SSD: "South Sudan", ESP: "Spain",
    LKA: "Sri Lanka", SDN: "Sudan", SUR: "Suriname", SWE: "Sweden", CHE: "Switzerland",
    SYR: "Syria", TWN: "Taiwan", TJK: "Tajikistan", TZA: "Tanzania", THA: "Thailand",
    TLS: "East Timor", TGO: "Togo", TON: "Tonga", TTO: "Trinidad and Tobago", TUN: "Tunisia",
    TUR: "Turkey", TKM: "Turkmenistan", TUV: "Tuvalu", UGA: "Uganda", UKR: "Ukraine",
    ARE: "United Arab Emirates", GBR: "United Kingdom", USA: "United States", URY: "Uruguay",
    UZB: "Uzbekistan", VUT: "Vanuatu", VAT: "Vatican City", VEN: "Venezuela", VNM: "Vietnam",
    YEM: "Yemen", ZMB: "Zambia", ZWE: "Zimbabwe",
    GRL: "Greenland", HKG: "Hong Kong", MAC: "Macau", PRI: "Puerto Rico", ESH: "Western Sahara",
    PSE: "Palestine", "X-KOSOVO": "Kosovo", "X-NORTHERN-CYPRUS": "Northern Cyprus",
    "X-SOMALILAND": "Somaliland",
};

export const FLAGS = {
    DZA: { title: "Flag of Algeria", colors: ["green", "red", "white"], words: ["green and white", "red crescent", "red five-pointed star"] },
    ARM: { title: "Flag of Armenia", colors: ["blue", "orange", "red"], words: ["red, blue, and orange"] },
    AUT: { title: "Flag of Austria", colors: ["red", "white"], words: ["red", "white"] },
    AZE: { title: "Flag of Azerbaijan", colors: ["blue", "green", "red", "white"], words: ["blue, red, and green", "white crescent"] },
    BHR: { title: "Flag of Bahrain", colors: ["red", "white"], words: ["white field", "red field", "white triangles"] },
    BGD: { title: "Flag of Bangladesh", colors: ["green", "red"], words: ["green field", "red disc"] },
    BEL: { title: "Flag of Belgium", colors: ["black", "red", "yellow"], words: ["black, yellow, and red"] },
    BWA: { title: "Flag of Botswana", colors: ["black", "blue", "white"], words: ["blue field", "black stripe", "white frame"] },
    BGR: { title: "Flag of Bulgaria", colors: ["green", "red", "white"], words: ["white, green and red"] },
    CHN: { title: "Flag of China", colors: ["gold", "red"], words: ["golden star", "Chinese red"] },
    COL: { title: "Flag of Colombia", colors: ["blue", "red", "yellow"], words: ["yellow band", "blue and red"] },
    CUB: { title: "Flag of Cuba", template: "Infobox National flag", colors: ["blue", "red", "white"], words: ["indigo blue", "white", "red equilateral triangle"] },
    DNK: { title: "Dannebrog", colors: ["red", "white"], words: ["white Nordic cross", "red background"] },
    EST: { title: "Flag of Estonia", colors: ["black", "blue", "white"], words: ["blue, black, and white"] },
    FIN: { title: "Flag of Finland", colors: ["blue", "white"], words: ["Sea-blue Nordic cross", "white field"] },
    GHA: { title: "Flag of Ghana", colors: ["black", "gold", "green", "red"], words: ["red, gold, and green", "black star"] },
    GRC: { title: "Flag of Greece", colors: ["blue", "white"], words: ["blue and white", "white Greek cross", "blue canton"] },
    GIN: { title: "Flag of Guinea", colors: ["green", "red", "yellow"], words: ["red, yellow and green"] },
    HND: { title: "Flag of Honduras", colors: ["blue", "white"], words: ["blue", "white", "five blue five-pointed stars"] },
    HUN: { title: "Flag of Hungary", colors: ["green", "red", "white"], words: ["red, white and green"] },
    ISL: { title: "Flag of Iceland", colors: ["blue", "red", "white"], words: ["blue field", "white-edged red Nordic cross"] },
    IND: { title: "Flag of India", colors: ["blue", "green", "orange", "white"], words: ["India saffron, white, and India green", "navy blue Ashoka Chakra"], note: "Saffron is grouped as orange; navy blue as blue. The Ashoka Chakra is included." },
    IRL: { title: "Flag of Ireland", colors: ["green", "orange", "white"], words: ["green, white and orange"] },
    ISR: { title: "Flag of Israel", colors: ["blue", "white"], words: ["White banner", "blue", "Star of David"] },
    CIV: { title: "Flag of Ivory Coast", colors: ["green", "orange", "white"], words: ["orange, white, and green"] },
    LTU: { title: "Flag of Lithuania", colors: ["green", "red", "yellow"], words: ["yellow, green and red"] },
    LUX: { title: "Flag of Luxembourg", colors: ["blue", "red", "white"], words: ["red, white and light blue"] },
    MLI: { title: "Flag of Mali", colors: ["gold", "green", "red"], words: ["green, gold, and red"] },
    FSM: { title: "Flag of the Federated States of Micronesia", colors: ["blue", "white"], words: ["light blue field", "four white five-pointed stars"] },
    MCO: { title: "Flag of Monaco", colors: ["red", "white"], words: ["red and white"] },
    NLD: { title: "Flag of the Netherlands", colors: ["blue", "red", "white"], words: ["red (bright vermilion), white, and cobalt blue"] },
    NGA: { title: "Flag of Nigeria", colors: ["green", "white"], words: ["green, white and green"] },
    MKD: { title: "Flag of North Macedonia", colors: ["red", "yellow"], words: ["yellow sun", "red field"] },
    PAK: { title: "Flag of Pakistan", colors: ["green", "white"], words: ["white star and crescent", "dark green field", "white stripe"] },
    PLW: { title: "Flag of Palau", colors: ["blue", "yellow"], words: ["light blue field", "yellow disk"] },
    POL: { title: "Flag of Poland", colors: ["red", "white"], words: ["white and red"] },
    ROU: { title: "Flag of Romania", colors: ["blue", "red", "yellow"], words: ["blue, yellow, and red"] },
    SLE: { title: "Flag of Sierra Leone", colors: ["blue", "green", "white"], words: ["light green, white and light blue"] },
    SOM: { title: "Flag of Somalia", colors: ["blue", "white"], words: ["white five-pointed star", "blue field"] },
    KOR: { title: "Flag of South Korea", colors: ["black", "blue", "red", "white"], words: ["white field", "red and blue"], extraEvidence: ["accompanied by four black [[Bagua|trigrams]]"], section: "Infobox — Design; lead — black trigrams" },
    SWE: { title: "Flag of Sweden", colors: ["blue", "yellow"], words: ["blue field", "yellow Nordic cross"] },
    CHE: { title: "Flag of Switzerland", colors: ["red", "white"], words: ["red square flag", "white Greek cross"] },
    THA: { title: "Flag of Thailand", colors: ["blue", "red", "white"], words: ["red, white, blue, white and red"] },
    TUN: { title: "Flag of Tunisia", colors: ["red", "white"], words: ["red field", "white sun-disc", "red five-pointed star", "red crescent"] },
    TUR: { title: "Flag of Turkey", colors: ["red", "white"], words: ["red field", "white crescent and star"] },
    UKR: { title: "Flag of Ukraine", colors: ["blue", "yellow"], words: ["blue and yellow"] },
    ARE: { title: "Flag of the United Arab Emirates", colors: ["black", "green", "red", "white"], words: ["green, white and black", "red bar"] },
    GBR: { title: "Union Jack", field: "Alt", colors: ["blue", "red", "white"], words: ["red cross", "red and white saltires", "white borders", "dark blue background"] },
    VNM: { title: "Flag of Vietnam", colors: ["gold", "red"], words: ["gold five-pointed star", "red field"] },
    YEM: { title: "Flag of Yemen", colors: ["black", "red", "white"], words: ["red, white and black"] },
    CAN: { title: "Flag of Canada", colors: ["red", "white"], words: ["red", "white", "maple leaf"] },
    USA: { title: "Flag of the United States", colors: ["blue", "red", "white"], words: ["red and white", "blue field"] },
    DEU: { title: "Flag of Germany", colors: ["black", "gold", "red"], words: ["black", "red", "gold"] },
    FRA: { title: "Flag of France", colors: ["blue", "red", "white"], words: ["blue, white, and red"] },
    JPN: { title: "Flag of Japan", colors: ["red", "white"], words: ["crimson disc", "white field"] },
    NPL: { title: "Flag of Nepal", colors: ["blue", "red", "white"], words: ["red field", "blue border", "white emblem"] },
    CHL: { title: "Flag of Chile", template: "Infobox National flag", colors: ["blue", "red", "white"], words: ["white and red", "blue square", "white five-pointed star"] },
    IDN: { title: "Flag of Indonesia", colors: ["red", "white"], words: ["red and white"] },
    RUS: { title: "Flag of Russia", colors: ["blue", "red", "white"], words: ["white, blue, and red"] },
    ZAF: { title: "Flag of South Africa", colors: ["black", "blue", "gold", "green", "red", "white"], words: ["red", "blue", "black", "green", "white", "Gold"] },
    BRA: { title: "Flag of Brazil", colors: ["blue", "green", "white", "yellow"], words: ["green field", "yellow rhombus", "blue disk", "white five-pointed stars"] },
};

export const CAPITALS = {
    USA: [{ title: "United States", name: "Washington, D.C.", roles: ["capital"], field: "capital" }],
    CAN: [{ title: "Canada", name: "Ottawa", roles: ["capital"] }],
    DEU: [{ title: "Germany", name: "Berlin", roles: ["capital"] }, { title: "Bonn", name: "Bonn", roles: ["federal ministries"], country: "Germany" }],
    FRA: [{ title: "France", name: "Paris", roles: ["capital"] }],
    JPN: [{ title: "Japan", name: "Tokyo", roles: ["capital"] }],
    NPL: [{ title: "Kathmandu", name: "Kathmandu", roles: ["capital"], country: "Nepal" }],
    CHL: [{ title: "Chile", name: "Santiago", roles: ["capital"] }, { title: "Valparaíso", name: "Valparaíso", roles: ["legislative seat"], country: "Chile" }],
    IDN: [{ title: "Indonesia", name: "Jakarta", roles: ["capital"] }],
    RUS: [{ title: "Russia", name: "Moscow", roles: ["capital"] }],
    ZAF: [
        { title: "Pretoria", name: "Pretoria", roles: ["executive capital"], country: "South Africa" },
        { title: "Cape Town", name: "Cape Town", roles: ["legislative capital"], country: "South Africa" },
        { title: "Bloemfontein", name: "Bloemfontein", roles: ["judicial capital"], country: "South Africa" },
    ],
    AUS: [{ title: "Australia", name: "Canberra", roles: ["capital"] }],
    BRA: [{ title: "Brazil", name: "Brasília", roles: ["capital"] }],
};

export const RANKINGS = {
    USA: {
        title: "List of United States cities by population",
        section: "50 states and the District of Columbia",
        populationHeading: 2, previousPopulationColumns: [3],
        headers: ["Municipality", "{{abbr|ST|State or district}}", "{year} estimate", "{year} census", "Change", "{year} land area", "{year} density", "Location"],
        subheaders: ["mi 2", "{{km2}}", "/ mi 2", "/ {{km2}}"],
        required: ["individual municipalities within their [[city limits|defined limits]]"],
        note: "Top ten incorporated places in the 50 states and DC, {year} estimates within municipal limits; consolidated-city balances follow Wikipedia's table. Territories aren't included.",
    },
    DEU: {
        title: "List of cities in Germany by population",
        section: "List",
        populationHeading: 3, matchingYearColumns: [0], previousPopulationColumns: [4],
        headers: ["{year} rank", "City", "State", "{year} estimate", "{year} estimate", "Growth", "Rank change", "{year} land area", "{year} population density", "Location"],
        required: ["individual municipalities within their [[City limits|defined limits]]"],
        note: "Top ten municipalities, {year} estimates. Wikipedia's table of cities above 100,000 is audited; these aren't metropolitan populations.",
    },
    CAN: {
        title: "List of the largest municipalities in Canada by population",
        section: "100 largest census subdivisions",
        populationHeading: 4, matchingYearColumns: [0], previousPopulationColumns: [5],
        headers: ["Rank ({year})", "Municipality", "Province", "Municipal status", "Population ({year})", "Population ({year})", "Change", "Land area (km 2 )", "Population density (/km 2 )"],
        required: ["only the population within a census subdivision's boundaries"],
        note: "{year} census municipal boundaries; the full 100-municipality table is audited. Calgary coordinates use a pinned 2019 Wikipedia revision with explicit values, not today's implicit Wikidata template.",
    },
};
